### ISSUE TITLE
As a community business employee I can switch between 2 login modes: centre visitor and centre manager

### ISSUE THREAD

**Issue by azayneeva** [FAC-11/DataPower#10]

**Comment by azayneeva** [comment]
![choose mode](https://user-images.githubusercontent.com/24795752/30977178-b151accc-a46e-11e7-9b8c-ddbe9c9f3ee0.png)

**Comment by rachaelcodes** [comment]
Comment from Sonja: 

> I like the one on the right. The one on the left could just say “visitor” and “staff”, to make it easier?
