### ISSUE TITLE
Move errors into separate file and import where needed.

### ISSUE THREAD

**Issue by ZooeyMiller** [FAC-11/DataPower#105]
You have repeated code which could be hidden away nicely in a separate file. 

You have `EMAIL_ERROR`, `NAME_ERROR` etc. These are used in multiple files, with the same code (e.g. in `signupcb.js` and `logincb.js`).

You could instead put these in a separate file called `errors.js` or something, and then import them where needed. This would make your components smaller, and more readable, and have less repetition in your code.

**Comment by azayneeva** [comment]
Done in #110
