### ISSUE TITLE
 As a CB employee I can define the days that the activities will be automatically displayed

### ISSUE THREAD

**Issue by RogeredBacon** [FAC-11/DataPower#118]
- [x] CB employees need to be able add and remove activities.
- [x] Activities should have a days attribute.
       - It would probably be useful to be able to edit the days even to 0 without having to delete the activity?
  
Relates to #119

**Comment by azayneeva** [comment]
shall we close this issue?

**Comment by azayneeva** [comment]
Will close this for now :)
