### ISSUE TITLE
Bug Fixing, Polishing, Testing and Styling

### ISSUE THREAD

**Issue by RogeredBacon** [FAC-11/DataPower#127]
4 Days

**Comment by finnhodgkin** [comment]
I'm going to pop any minor syntax issues I find here so they can be fixed when there's time.

All of the handleChange functions could use ES6 to create the object with a variable key:
```js
  handleChange = e => {
    let newState = {};
    newState[e.target.name] = e.target.value;
    this.setState(newState);
  };
```
Could be:
```js
  handleChange = e => this.setState({ [e.target.name]: e.target.value });
```

**Comment by RogeredBacon** [comment]
Closing this - the most successful issue on the project :sparkling_heart:
