### ISSUE TITLE
Use bodyparser instead of req.on('data')

### ISSUE THREAD

**Issue by finnhodgkin** [FAC-11/DataPower#131]
The reason bodyparser isn't working is that all the fetch requests from the front end have a content type of text, not `application/json`. If you add the correct content type header to all your React fetches then bodyparser will work again:

```js
  headers = new Headers({
    Authorization: localStorage.getItem('token'),
    'Content-Type': 'application/json'
  });
```
  Alternatively you could [configure bodyparser to accept other content types](https://github.com/expressjs/body-parser#bodyparserjsonoptions) (I wouldn't recommend this option).

**Comment by azayneeva** [comment]
shall we close this issue? as everything seems to be done properly now 👍
