### ISSUE TITLE
Form validation shouldn't default to passing

### ISSUE THREAD

**Issue by finnhodgkin** [FAC-11/DataPower#133]
In `main.js` there's a case statement that determines which error should be displayed. Currently the final default is to pass as though nothing went wrong - IMO it would be safer to have the first case as the success case and then a final default with an `Oh no something weird went wrong` error. That way if you get something unexpected from the server it won't just move on to the next screen.

Not this:
```js
  .then(data => {
        switch (data) {
          case 'email':
            this.setError([errorMessages.EMAIL_ERROR]);
            break;

          ...rest of the error cases

          default:
            this.props.history.push('/visitor/signup/step2');
            break;
        }
      })
```

But this:
```js
  .then(data => {
        switch (data) {
          case false:
            this.props.history.push('/visitor/signup/step2');
            break;

          ...rest of the error cases

          default:
            this.setError([errorMessages.GENERIC_ERROR]);
            break;
        }
      })
```

**Comment by azayneeva** [comment]
maybe we can close this as well?

**Comment by RogeredBacon** [comment]
Yup this is merged now
