### ISSUE TITLE
As a user I can print out my QR code combined with a logo

### ISSUE THREAD

**Issue by rachaelcodes** [FAC-11/DataPower#16]
- [x] check with Sonja what printing options we might be able to offer
- [x] Is there a module for creating a document and sending it to the printer?

**Comment by rachaelcodes** [comment]
In case this helps, cheap domestic printers look like they can print on A7 size (checking the manual for a printer I bought for £30 8 years ago)

**Comment by rachaelcodes** [comment]
have talked it through with @RogeredBacon and @azayneeva - perhaps this is something for a future sprint, as it involves hardware purchasing decisions

**Comment by RogeredBacon** [comment]
As a user I can print out my QR code combined with a logo.

- [ ] Automatically combining QR Code image, logo image and other info
- [ ] Printing image

**Comment by RogeredBacon** [comment]
So I've found two modules, One that can create a pdf combining images, text, formatting etc :https://www.npmjs.com/package/pdfmake

and one that can print pdf's, without having to leave the app:http://printjs.crabbly.com/#documentation
It can also print things straight from the server without having to download them locally
