### ISSUE TITLE
Should we get someone who knows what they are doing to help us with design/styling?

### ISSUE THREAD

**Issue by RogeredBacon** [FAC-11/DataPower#178]
Finn made the excellent points that:
1. The design and styling of the app is pretty bad and has remained unchanged since the start of the project.
2. We don't know what we are doing in terms of designing a usable and attractive app.

Would it be worth talking to a designer? If we liked their ideas we could hire them for a couple of days to help implement?

Finn already started to look into this but maybe we should think about using Google Materials to make our app more 'appy' and versatile? We would have to do a Tech Spike before that though of course.

I think it's definitely worth redesigning whether we do it ourselves or otherwise, and as we plan to take some time to re-factor, now would probably be the time to do it.

**Comment by astroash** [comment]
I'm pro redesgin :) Do we have branding guidelines from Power to Change/ Twine?

**Comment by astroash** [comment]
@RogeredBacon can this be closed?

**Comment by RogeredBacon** [comment]
Yus
