### ISSUE TITLE
Add Google Material Design

### ISSUE THREAD

**Issue by finnhodgkin** [FAC-11/DataPower#179]
The app could do with a redesign. In the meantime while a decision is made about #178, it would be pretty easy to move the whole thing over to Material UI.

I've made a set of design commits for the admin sections that I'll add now so you can decide if it's what you're after/show them to the PO :+1:. 

Features:
- An app bar for all pages
- Error messages underneath text inputs
- Text inputs with floating labels
- Basically no CSS required

**Comment by RogeredBacon** [comment]
Not relevant any more due to redesigns
