### ISSUE TITLE
As a user I will receive my QR code through my email automatically; a CB employee will also receive a copy.

### ISSUE THREAD

**Issue by rachaelcodes** [FAC-11/DataPower#35]
- [x] emailed to users who have provided email addresses

See: https://github.com/rachaelcodes/mailer for an example using the mailer module. Some comments in #4

**Comment by RogeredBacon** [comment]
As a user I will receive my QR code through my email automatically; a CB employee will also receive a copy.

- [ ] Implement automatic email sending
- [ ] Formatting email and attaching QR Code

**Comment by azayneeva** [comment]
we are going to use this module: https://www.npmjs.com/package/postmark

**Comment by RogeredBacon** [comment]
Boom :boom:
