### ISSUE TITLE
As an existing user: I can easily sign in with my QR code (on paper or phone screen)

### ISSUE THREAD

**Issue by rachaelcodes** [FAC-11/DataPower#6]
- [x] QR reading 
- [x] connect instascan output to a database query
- [x] add validation for database query

**Comment by rachaelcodes** [comment]
![qr scan](https://user-images.githubusercontent.com/23265724/30977022-39e3d62e-a46e-11e7-84b0-61274ae32fc3.png)

**Comment by azayneeva** [comment]
Here is the test code: [test.zip](https://github.com/FAC-11/DataPower/files/1341560/test.zip)

- we can generate QR code 
- read it from png files

**Comment by RogeredBacon** [comment]
Using [this](https://github.com/schmich/instascan) module we will read the qr codes, and check them against the database.

**Comment by rachaelcodes** [comment]
Comment from Sonja:

> “What information are we storing?
> Your name, sex, age, and reason for visiting today, as well as the time and date of your visit.
> Why are we collecting this information?
> We are always trying to improve what we offer you. By signing in, you are helping us make our services better.”

**Comment by rachaelcodes** [comment]
possible problems:
- server problem - 500 error message (will be triggered by error handler)

Go to reception:
- QR code is damaged and can't be read
- reader problem and QR codes can't be deciphered

Check you have the right QR code and sign in
- wrong QR code scanned (deliberately or not)

User not registered: 
- go back to sign up
![qr scanning error](https://user-images.githubusercontent.com/23265724/31384729-17fc1f3c-adb8-11e7-8dc5-0fac3f3f6854.png)
