### ISSUE TITLE
write README

### ISSUE THREAD

**Issue by rachaelcodes** [FAC-11/DataPower#63]
https://hackmd.io/BwVgnAzALARgZgNgLTDFAxkqBGeSCGADCIUgCYBM2YA7BURcGfkA

**Comment by azayneeva** [comment]
<img width="781" alt="screen shot 2017-10-12 at 15 49 47" src="https://user-images.githubusercontent.com/24795752/31502482-1a0974ce-af65-11e7-87fe-58b6968a305b.png">
