### ISSUE TITLE
[Suggestion] Start using prettier for consistent style

### ISSUE THREAD

**Issue by ZooeyMiller** [FAC-11/DataPower#80]
I really like [Prettier](https://github.com/prettier/prettier) and would really recommend it. 

It will make your code style consistent throughout the whole project, and quite often makes things easier to read.

If you do decide to use prettier (you don't have to, just a suggestion), I'd recommend making a single PR with all of the files being reformatted (but with no new code being added), as otherwise when you make PRs with actual code changes the git diffs can be hard to read. 

Feel free to close this issue if you decide not to use it, or close with a PR where you use it to reformat all the code if you do decide to use it.

**Comment by azayneeva** [comment]
@ZooeyMiller , thank you for the suggestion. We will most probably use it if you recommend it to us, but could you please clarify what is the actual difference between Prettier and Beautify?

**Comment by ZooeyMiller** [comment]
Prettier is just very opinionated, I think in general it's similar to Beautify, though I haven't used Beautify much.

I think Beautify offers you more configuration options, whereas Prettier has already decided on its own configuration mostly.

I think either would be fine, but using some kind of beautifier/something to keep code style consistent should make your code a little cleaner and easier to read.
