### ISSUE TITLE
Fix and refactor error messages on signup page

### ISSUE THREAD

**Issue by RogeredBacon** [FAC-11/DataPower#91]
They're currently not working as hoped and the code is a bit of a mess and needs to be refactored from the tons of 'if' statements it is currently.

We need to work out exactly how we want multiple errors to be displayed:

1. What errors takes priority?
2. Should we check the password as we type?
3. Should we display multiple errors or one at a time?

**Comment by ZooeyMiller** [comment]
some notes of things to refactor: 

https://github.com/FAC-11/DataPower/pull/92#discussion_r153777068

https://github.com/FAC-11/DataPower/pull/92#discussion_r154140436

https://github.com/FAC-11/DataPower/pull/92#discussion_r154141040

**Comment by azayneeva** [comment]
https://egghead.io/lessons/egghead-make-dynamic-forms-with-react  - an example of how to display error messages dynamically

**Comment by RogeredBacon** [comment]
Completed, opening new issue to implement validation as you type.
