### ISSUE TITLE
Follow the postmark guide for proper formatting for emails

### ISSUE THREAD

**Issue by RogeredBacon** [FAC-11/DataPower#96]
We should make sure that all of our emails are properly formatted with all of the appropriate meta-data: [Transactional email best practices](https://postmarkapp.com/guides/transactional-email-best-practices)

[Password reset email best practices](https://postmarkapp.com/guides/password-reset-email-best-practices)

**Comment by RogeredBacon** [comment]
The emails should look better now but we'll have to wait till we ask for copy from Sonja to get them finalised :shipit:

**Comment by azayneeva** [comment]
Close this issue as we've done it :)
